project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('review.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('ckeditor', include('ckeditor_uploader.urls')),
    
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('<slug>', PostDetailView.as_view(), name='postdetail'),
    path('category/<slug:slug>', CategoryDetailView.as_view(), name='filter_category'),
    path('subcategory/<slug:slug>', SubCategoryDetailView.as_view(), name='filter_subcategory'),
    path('search/', SearchView.as_view(), name='search'),
    path('contact_us/', ContactView.as_view(), name='contact'),
    path('admins/create', AdminPostCreateView.as_view(), name='create_post'),
    path('admins/<int:pk>/delete',
         AdminPostDeleteView.as_view(), name='delete_post'),
    path('adminedit/<int:pk>', AdminPostUpdateView.as_view(), name='edit_post'),
    path('search', SearchView.as_view(), name='search'),
    path('admins/post/', AdminPostListView.as_view(), name='list_post'),
]

review/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from autoslug import AutoSlugField
from tinymce.models import HTMLField
from ckeditor_uploader.fields import RichTextUploadingField
from autoslug import AutoSlugField
from PIL import Image
from io import BytesIO
from django.core.files import File
# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    date_created = models.DateTimeField(auto_now_add=True)

class Contact(models.Model):
	first_name = models.CharField(max_length=256)
	email = models.EmailField(max_length=256, null=True, blank=True)
	message = models.TextField(null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.first_name

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to='cat_img', blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to='subcat_img', blank=True, null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Post(models.Model):
    class PostManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')

    sta = (
        ('published', 'published'), 
        ('draft', 'draft'),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.PROTECT, blank=True, null=True)
    title = models.CharField(max_length=500)
    slug = AutoSlugField(populate_from='title')
    image_1 = models.ImageField(upload_to='post_image', null=True)
    excerpt = models.TextField(null=True, blank=True)
    content = RichTextUploadingField()
    date_created = models.DateTimeField(auto_now_add=True)
    view_count = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=30, choices=sta, default='published')
    # objects  = PostManager()
    
    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        new_image = self.reduce_image_size(self.image_1)
        self.image_1 = new_image
        super().save(*args, **kwargs)

    def reduce_image_size(self, profile_pic):
        print(profile_pic)
        img = Image.open(profile_pic)
        thumb_io = BytesIO()
        img.save(thumb_io, 'jpeg', quality=50)
        new_image = File(thumb_io, name=profile_pic.name)
        return new_image

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,  null=True, blank=True)
    name = models.CharField(max_length=150)
    email = models.EmailField(null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.post.title

templates/add_post.html
{% extends "base.html" %}
{% load static %}
{% block title %}
add post
{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
<h2>Add post</h2>
<br>
<div class="form-group">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy} }}
        <button type="submit" class="btn btn-primary"></button>
    </form>
</div>
  
{% endif %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="icon" href="{% static 'logo1.png' %}">
        {% block ogmeta %}{% endblock ogmeta %}
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>{% block title %} {% endblock %}</title>
    <style>
      #hint_id_username,
      #hint_id_password1,
      #hint_id_new_password1,
      #hint_id_password2 {
        display: none;
      }

      a:link {
        text-decoration: none;
        color: black;
      }

      a:visited {
        color: black;
      }
      img {
        width: 500px;
        height: 500px;
      }
      /* .card-horizontal {
  display: flex;
  flex: 1 1 auto;
} */
    </style>
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-transparent" style="position:sticky">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">TanoClass</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a href="{% url 'main:index' %}" class='nav-link'>Home</a>
            </li>
            <li class="nav-item active">
              <a href="{% url 'main:index' %}" class='nav-link'>All </a>
            </li>
            <li class="nav-item active">
              <a href="{% url 'main:index' %}" class='nav-link'>About</a>
            </li>
            <li class="nav-item active">
              <a href="{% url 'main:contact' %}" class='nav-link'>Contact</a>
            </li>
            

          </ul>
        </div>

      </div>
    </nav>
  <body>
    {% block header %} {% endblock header %}
    {% block content %} {% endblock %}
    <!-- Footer-->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; parksontano.com 2022</p>
  </div>
</footer>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'scripts.js' %}"></script>
    <script src="{% static 'js/form-validation.js' %}"></script>
  </body>
</html>

templates/category_detail.html
{% extends "base.html" %}
{% block header %}
<header class="masthead" style="background-image: url({{ca.image.url}})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{{ca.name}}</h1>
                    <span class="subheading">Just Learn</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
<div class="row gx-4 gx-lg-5 justify-content-center">
    
    <div class="col-md-10 col-lg-8 col-xl-7">
       {% for p in post %}
        <div class="post-pmain">
            <a href="{% url 'main:postdetail' p.slug %}">
                <h2 class="post-title">{{p.title}}</h2>
                <h3 class="post-subtitle">{{p.excerpt}}</h3>
            </a>
            <p class="post-meta">
                Posted by
                <a href="#!">{{p.author}}</a>
                on {{p.date_created}}
                {{ p.comment_set.all.count }} comment
                {{p.view_count}} seen
            </p>

        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% endfor %}  
        
          
    </div>

<div class="col-lg-4">
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Enter search term..."
                            aria-label="Enter search term..." aria-describedby="button-search" />
                        <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                    </div>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4">
                <div class="card-header">SubCategories</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6 col-lg-12">
                            <ul class="list-unstyled mb-0">
                                    <ul>
                                        {% for sub in subcategory %}
                                        <li>
                                            <a href="{% url 'main:filter_subcategory' sub.slug %}">
                                                {{sub.name}}
                                            </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                        </div>
                    </div>
                </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4">
                <div class="card-header">Recommended</div>
                <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use,
                    and feature the Bootstrap 5 card component!</div>
            </div>

</div>
{% endblock content %}

templates/contact_us.html
{% extends "base.html" %}
{% block title %}
contact_us
{% endblock title %}
{% load static %}
<!-- Custom styles for this template -->

{% block content %}
<div class="container">
  <main>
    <div class="py-5 text-center p-4">
      <h2>Send Us A Message</h2>
    </div>
    <div class="col-md-7 col-lg-8 gx-4 gx-lg-5 justify-content-center">
      <form class="needs-validation" method="post" action="" novalidate>
        {% csrf_token %}
        <div class="row g-3">
          <div class="col-sm-12">
            <label for="firstName" class="form-label">First name</label>
            {{form.first_name}}
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>

          <div class="col-12">
            <label for="email" class="form-label">Email</span></label>
            {{form.email}}
            <div class="invalid-feedback">
              Please enter a valid email address
            </div>
            <div class="col-md-3 col-lg-12">
              <label for="zip" class="form-label">Message</label>
              {{form.message}}
              <div class="invalid-feedback">
                Message is Require
              </div>
            </div>
          </div>

          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" type="submit">Submit</button>
      </form>

    </div>
</div>

</main>
</div>


{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} home {% endblock title %}
{% block header %}
<header class="masthead" style="background-image: url('{% static 'logo1.png' %}'); height: 100vh; opacity: 1;">
    <div class="container position-relative px-4 px-lg-5 ">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h3>Welcome to Parkson Tano</h3>
                    <span class="subheading">
                        Let's Learn and grow
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}

<!-- Page content-->
<div class="container-fluid">
    <div class="row mt-1">
        <!-- Blog entries-->
        <div class="col-lg-8">
            <!-- Featured blog post-->
            <div class="card mb-4">
                <a href="{{post.first.image_1.url}}"><img class="card-img-top" src="{{post.first.image_1.url}}" alt="..."
                        style="" /></a>
                <div class="card-body">
                    <div class="small text-muted">{{post.first.date_created}}</div>
                    <h2 class="card-title">{{post.first.title}}</h2>
                    <p class="card-text">{{post.first.excerpt}}</p>
                    <p class="mute-text">{{post.first.category}}</p>
                    <p class="mute-text">{{post.first.subcategory}}
                        {{post.first.comment_set.all.count}} Comment
                        {{ post.first.view_count }}
                    </p>
                    <a class="btn btn-danger" href="{% url 'main:postdetail' post.first.slug %}">Read more →</a>
                </div>
            </div>
            <!-- Nested row for non-featured blog posts-->
            <div class="row mb-2">
                {% for p in post %}
                <div class="col-lg-6">
                    <!-- Blog post-->

                    <div class="card mb-4">
                        <div class='card-horizontal'>

                            <a href="{{p.image_1.url}}"><img class="card-img" src="{{p.image_1.url}}" alt="..." 
                                style='height:15rem' /></a>


                            <div class="card-body">
                                <div class="small text-muted">{{p.date_created|timesince}}</div>
                                <h2 class="card-title h4">{{p.title}}</h2>
                                <p class="card-text">{{p.excerpt}}</p>
                                <p class="mute-text">{{p.category}}</p>
                                <p class="mute-text">{{p.subcategory}}
                                    {{p.comment_set.all.count}} Comment{{p.comment_set.all.count|pluralize }}
                                    {{ p.view_count }}
                                </p>

                                <a class="btn btn-danger" href="{% url 'main:postdetail' p.slug %}">Read more →</a>
                            </div>
                        </div>

                    </div>
                    <!-- Blog post-->
                </div>
                {% endfor %}
            </div>
            <!-- Pagination-->
            <nav>
                <ul class="pagination" aria-label="...">
                    {% if product_list.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ post.previous_page_number }}" class="page-link y-5">Previous Posts</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a href="" class="page-link" tabindex="-1" aria-disabled="true">Previous Post</a>
                    </li>
                    {% endif %}

                    {% for i in product_list.paginator.page_range %}

                    {% if i == product_list.number %}
                    <li class="page-item active"> <a class="page-link" disabled> {{ i}}</a> </li>
                    {% else %}
                    <li class="page-item"> <a href="?page={{i}}" class="page-link"> {{ i}}</a> </li>
                    {% endif %}
                    {% endfor %}

                    {% if product_list.has_next %}
                    <li class="page-item">
                        <a href="?page={{ product_list.next_page_number }}" class="page-link">Next Post</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a href="" class="page-link" tabindex="-1" aria-disabled="true">Next Post</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">

                    <form action="{% url 'main:search' %}" method="GET">
                        <div class="input-group">
                            {% csrf_token %}
                            <input class="form-control" type="text" placeholder="Enter search term..."
                                aria-label="Enter search term..." aria-describedby="button-search" name='keyword' />
                            <button class="btn btn-primary">Go!</button>
                        </div>
                    </form>



                </div>
            </div>

            <!-- Categories widget-->
            <div class="card mb-4">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12 col-lg-12">
                            <ul class="list-unstyled mb-0">
                                {% for cat in all_categories %}
                                <li class="mb-2"><a href="{% url 'main:filter_category' cat.slug %}">
                                        <strong>
                                            {{cat.name}}
                                        </strong>
                                    </a>
                                    <ul>
                                        {% for sub in cat.subcategory_set.all %}
                                        <li>
                                            <a href="{% url 'main:filter_subcategory' sub.slug %}">
                                                {{sub.name}}
                                            </a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4">
                <div class="card-header">Recent Post</div>
                <div class="card-body">
                    {% for p in recent_post %}
                    <div class="post-pmain">
                        <a href="{% url 'main:postdetail' p.slug %}">
                            <h2 class="post-title">{{p.title}}</h2>
                            <h3 class="post-subtitle">{{p.excerpt|slice:80}}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">{{p.author}}</a>
                            on {{p.date_created|timesince}}
                        </p>

                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock content%}

templates/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{{post.slug}}
{% endblock title %}
{% block header %}
<header class="masthead" style="background-image: url({{post.image_1.url}})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{{post.title}}</h1>
                    <span class="subheading">Just Learn</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
<!-- Page content-->
<div class='container-fluid'>
  <div class="row mt-4">
    <!-- Blog entries-->
    <div class="col-lg-8">
      <!-- Featured blog post-->
      <div class="card mb-4 col-sm-12">
        <div class="card-body">

          <p class="card-text">{{post.content|safe}}</p>

        </div>
      </div>
      <!-- Nested row for non-featured blog posts-->
      <div class="row">
        <div class="col-lg-12 mb-3">
          <!-- Blog post-->
          <h2>Leave your comment or Question!</h2>
          <div id="comments_section">
            <form method="POST" class='needs-validation'>
              {% csrf_token %}
              <div class="form-group">
                {{ comment_form|crispy }}

                <button class="btn btn-info" type="submit">Add comment <i class="fas fa-comments"></i></button>
              </div>
            </form>

            {% if comments %}
            <strong class="text-secondary">{{ post.comment_set.all.count }}
              Comment{{ post.comment_set.all.count|pluralize }}</strong>
            <hr>
            <ul class="list-group">
              {% for comment in comments %}
              <li class="list-group-item">
                <div>
                  <span>
                    <strong class="text-info">{{ comment.name }} </strong>
                    <small class="text-muted">{{ comment.date_created }}</small>
                  </span>
                  <p>
                    {{ comment.content|safe }}
                  </p>
                </div>
              </li>
              {% endfor %}
            </ul>
            {% else %}
            <strong class="text-secondary">No comments yet...</strong>
            {% endif %}

          </div>
        </div>


        <!-- Blog post-->
      </div>
      <!-- Pagination-->
    </div>
    <!-- Side widgets-->
    <div class="col-lg-4">
      <!-- Search widget-->
      <div class="card mb-4">
        <div class="card-header">Search</div>
        <div class="card-body">

          <form action="{% url 'main:search' %}" method="GET">
            <div class="input-group">
              {% csrf_token %}
              <input class="form-control" type="text" placeholder="Enter search term..."
                aria-label="Enter search term..." aria-describedby="button-search" name='keyword' />
              <button class="btn btn-primary">Go!</button>
            </div>
          </form>
        </div>
      </div>
    <!-- Categories widget-->
    <div class="card mb-4">
      <div class="card-header">Categories</div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-6 col-lg-12">
            <ul class="list-unstyled mb-0">
              {% for cat in all_categories %}
              <li class="mb-2"><a href="{% url 'main:filter_category' cat.slug %}">
                  <strong>
                    {{cat.name}}
                  </strong>
                </a>
                <ul>
                  {% for sub in cat.subcategory_set.all %}
                  <li>
                    <a href="{% url 'main:filter_subcategory' sub.slug %}">
                      {{sub.name}}
                    </a>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- Side widget-->
    <div class="card mb-4">
      <div class="card-header">Recent Post</div>
      <div class="card-body">
        {% for p in recent_post %}
        <div class="post-pmain">
          <a href="{% url 'main:postdetail' p.slug %}">
            <h2 class="post-title">{{p.title}}</h2>
            <h3 class="post-subtitle">{{p.excerpt}}</h3>
          </a>
          <p class="post-meta">
            Posted by
            <a href="#!">{{p.author}}</a>
            on {{p.date_created|timesince}}
          </p>

        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% endfor %}
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>


{% endblock content%}

templates/search_result.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<header class="masthead" style="background-image: url('{% static 'home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">Center of Diversity</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
<div class="row gx-4 gx-lg-5 justify-content-center">

    <div class="col-md-10 col-lg-8 col-xl-7">
        {% for res in result %}
        <div class="post-pmain">
            <a href="{% url 'main:postdetail' res.slug %}">
                <h2 class="post-title">{{res.title}}</h2>
                <h3 class="post-subtitle">{{res.excerpt}}</h3>
            </a>
            <p class="post-meta">
                Posted by
                <a href="#!">{{res.author}}</a>
                on {{res.date_created|timesince}}
                {{ res.comment_set.all.count }} comment
                {{res.view_count}} seen
            </p>

        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% empty %}
        <li>
            not found
        </li>
        {% endfor %}


    </div>

    <div class="col-lg-4 mt-3" >
        <!-- Side widgets-->
        <div class="col-lg-12">
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">

                    <form action="{% url 'main:search' %}" method="GET">
                        <div class="input-group">
                            {% csrf_token %}
                            <input class="form-control" type="text" placeholder="Enter search term..."
                                aria-label="Enter search term..." aria-describedby="button-search" name='keyword' />
                            <button class="btn btn-primary">Go!</button>
                        </div>
                    </form>



                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6 col-lg-12">
                            <ul class="list-unstyled mb-0">
                                {% for cat in all_categories %}
                                <li class="mb-2"><a href="{% url 'main:filter_category' cat.slug %}">
                                        <strong>
                                            {{cat.name}}
                                        </strong>
                                    </a>
                                    <ul>
                                        {% for sub in cat.subcategory_set.all %}
                                        <li>
                                            <a href="{% url 'main:filter_subcategory' sub.slug %}">
                                                {{sub.name}}
                                            </a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4">
                <div class="card-header">Recommended</div>
                <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use,
                    and feature the Bootstrap 5 card component!</div>
            </div>
        </div>

    </div>
    {% endblock content %}

templates/subcategory_detail.html
{% extends "base.html" %}
{% block header %}
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{{subcategory.name}}</h1>
                    <span class="subheading">Just Learn</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
<div class="row gx-4 gx-lg-5 justify-content-center">
    {% for p in post %}
    <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-pmain">
            <a href="{% url 'main:postdetail' p.slug %}">
                <h2 class="post-title">{{p.title}}</h2>
                <h3 class="post-subtitle">{{p.excerpt}}</h3>
            </a>
            <p class="post-meta">
                Posted by
                <a href="#!">{{p.author}}</a>
                on {{p.date_created}}
            </p>

        </div>
        <!-- Divider-->
        <hr class="my-4" />
    </div>
    {% endfor %}

</div>
    {% endblock content %}